In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('./pre_procesing_output.csv')

In [20]:
data.head()

population  suicides/100kpop  gdp_for_year($)  gdp_per_capita($)  \
0     2709600             31.85       2156624900                796   
1     2764300             32.46       2126000000                769   
2     2803100             33.40       2335124988                833   
3     2822500             18.00        709452584                251   
4     2807300             32.56       1228071038                437   

   suicides_no  
0           73  
1           63  
2           68  
3           47  
4           73

In [47]:
aux = data['suicides_no'].values

def func(n): 
    return [n]

res = map(func, aux) 
y = np.asarray(list(res))
print(y)
# np.asarray(y)
# print(y)

[[  73]
 [  63]
 [  68]
 ...
 [1835]
 [1950]
 [2095]]


In [26]:
del data['suicides_no']
X = data.values
print(X)

[[2.70960000e+06 3.18500000e+01 2.15662490e+09 7.96000000e+02]
 [2.76430000e+06 3.24600000e+01 2.12600000e+09 7.69000000e+02]
 [2.80310000e+06 3.34000000e+01 2.33512499e+09 8.33000000e+02]
 ...
 [2.63818300e+07 7.75300000e+01 5.18215733e+10 1.96400000e+03]
 [2.68389240e+07 7.88600000e+01 5.76904535e+10 2.15000000e+03]
 [2.73135070e+07 8.51200000e+01 6.30670772e+10 2.30900000e+03]]


In [48]:
print(y)

[[  73]
 [  63]
 [  68]
 ...
 [1835]
 [1950]
 [2095]]


In [49]:
print(X)

[[2.70960000e+06 3.18500000e+01 2.15662490e+09 7.96000000e+02]
 [2.76430000e+06 3.24600000e+01 2.12600000e+09 7.69000000e+02]
 [2.80310000e+06 3.34000000e+01 2.33512499e+09 8.33000000e+02]
 ...
 [2.63818300e+07 7.75300000e+01 5.18215733e+10 1.96400000e+03]
 [2.68389240e+07 7.88600000e+01 5.76904535e+10 2.15000000e+03]
 [2.73135070e+07 8.51200000e+01 6.30670772e+10 2.30900000e+03]]


In [30]:
from sklearn import linear_model
regr = linear_model.ElasticNet(random_state=0)
regr.fit(X, y)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

In [32]:
regr.predict([[2709600, 31.85, 2156624900, 796]])

array([-1836.665219])

In [50]:
from sklearn import linear_model
clf = linear_model.MultiTaskLasso(alpha=0.1)
clf.fit(X, y)

MultiTaskLasso(alpha=0.1, copy_X=True, fit_intercept=True, max_iter=1000,
        normalize=False, random_state=None, selection='cyclic', tol=0.0001,
        warm_start=False)

In [51]:
clf.predict([[2709600, 31.85, 2156624900, 796]])

array([[-1836.74253043]])