In [39]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

data = pd.read_csv('./pre_procesing_output.csv')

In [40]:
# dataT -> data training
# dataTest -> data test

dataT = data.sample(frac=0.7, replace=False, random_state=1)

dataTest = data.sample(frac=0.3, replace=False, random_state=2)

# dataT.describe()
# dataTest.describe()

In [11]:
data.head()

population  suicides/100kpop  gdp_for_year($)  gdp_per_capita($)  \
0     2709600             31.85       2156624900                796   
1     2764300             32.46       2126000000                769   
2     2803100             33.40       2335124988                833   
3     2822500             18.00        709452584                251   
4     2807300             32.56       1228071038                437   

   suicides_no  
0           73  
1           63  
2           68  
3           47  
4           73

In [41]:
y = dataT['suicides_no'].values

In [32]:
del dataT['suicides_no']
X = dataT.values
print(X)

[[5.89416210e+07 7.91400000e+01 2.62942651e+11 4.46100000e+03]
 [2.87980500e+06 4.07690000e+02 4.34768734e+10 1.50970000e+04]
 [4.02670700e+06 1.21770000e+02 2.69917520e+11 6.70320000e+04]
 ...
 [4.91561400e+06 2.55520000e+02 1.39552983e+11 2.83900000e+04]
 [2.32000000e+05 1.10120000e+02 5.58853301e+09 2.40890000e+04]
 [4.68142070e+07 4.66540000e+02 1.12267915e+12 2.39820000e+04]]


In [33]:
print(y)

[ 3754  1018   458 ...  1095    22 12174]


In [34]:
print(X)

[[5.89416210e+07 7.91400000e+01 2.62942651e+11 4.46100000e+03]
 [2.87980500e+06 4.07690000e+02 4.34768734e+10 1.50970000e+04]
 [4.02670700e+06 1.21770000e+02 2.69917520e+11 6.70320000e+04]
 ...
 [4.91561400e+06 2.55520000e+02 1.39552983e+11 2.83900000e+04]
 [2.32000000e+05 1.10120000e+02 5.58853301e+09 2.40890000e+04]
 [4.68142070e+07 4.66540000e+02 1.12267915e+12 2.39820000e+04]]


### Training

In [35]:
from sklearn import linear_model
regr = linear_model.ElasticNet(random_state=0)
regr.fit(X, y)

ElasticNet(alpha=1.0, copy_X=True, fit_intercept=True, l1_ratio=0.5,
      max_iter=1000, normalize=False, positive=False, precompute=False,
      random_state=0, selection='cyclic', tol=0.0001, warm_start=False)

### Evaluation

In [36]:
regr.predict([[2709600, 31.85, 2156624900, 796]])

array([-1914.21093398])